# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings

source: ./source

title: Peer Review - News and Blog 
tagline: >-
  Updates and news from Peer Review, a diamond open access, open source
  scientific and academic publishing platform. 
email: dbingham@theroadgoeson.com 
description: >- 
  Updates and news from Peer Review, a diamond open access, open source
  scientific and academic publishing platform.
url: "http://blog.peer-review.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: :title 

# Defaults
defaults:
  - 
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
  - 
    scope: 
      path: ""
    values:
      layout: "default"

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-seo-tag
